// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: rates.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_rates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_rates_proto_rawDescGZIP(), []int{0}
}

type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BestAsk       string                 `protobuf:"bytes,3,opt,name=best_ask,json=bestAsk,proto3" json:"best_ask,omitempty"`
	BestBid       string                 `protobuf:"bytes,4,opt,name=best_bid,json=bestBid,proto3" json:"best_bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_rates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_rates_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatesResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRatesResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetRatesResponse) GetBestAsk() string {
	if x != nil {
		return x.BestAsk
	}
	return ""
}

func (x *GetRatesResponse) GetBestBid() string {
	if x != nil {
		return x.BestBid
	}
	return ""
}

var File_rates_proto protoreflect.FileDescriptor

const file_rates_proto_rawDesc = "" +
	"\n" +
	"\vrates.proto\x12\x05rates\"\x11\n" +
	"\x0fGetRatesRequest\"v\n" +
	"\x10GetRatesResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bbest_ask\x18\x03 \x01(\tR\abestAsk\x12\x19\n" +
	"\bbest_bid\x18\x04 \x01(\tR\abestBid2K\n" +
	"\fRatesService\x12;\n" +
	"\bGetRates\x12\x16.rates.GetRatesRequest\x1a\x17.rates.GetRatesResponseB*Z(github.com/booler007/gRPC_currentrate/pbb\x06proto3"

var (
	file_rates_proto_rawDescOnce sync.Once
	file_rates_proto_rawDescData []byte
)

func file_rates_proto_rawDescGZIP() []byte {
	file_rates_proto_rawDescOnce.Do(func() {
		file_rates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rates_proto_rawDesc), len(file_rates_proto_rawDesc)))
	})
	return file_rates_proto_rawDescData
}

var file_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rates_proto_goTypes = []any{
	(*GetRatesRequest)(nil),  // 0: rates.GetRatesRequest
	(*GetRatesResponse)(nil), // 1: rates.GetRatesResponse
}
var file_rates_proto_depIdxs = []int32{
	0, // 0: rates.RatesService.GetRates:input_type -> rates.GetRatesRequest
	1, // 1: rates.RatesService.GetRates:output_type -> rates.GetRatesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rates_proto_init() }
func file_rates_proto_init() {
	if File_rates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rates_proto_rawDesc), len(file_rates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rates_proto_goTypes,
		DependencyIndexes: file_rates_proto_depIdxs,
		MessageInfos:      file_rates_proto_msgTypes,
	}.Build()
	File_rates_proto = out.File
	file_rates_proto_goTypes = nil
	file_rates_proto_depIdxs = nil
}
